equipe/urls.py
from django.urls import path
from . import views

app_name = 'equipe'  # Defina o namespace para sua aplicação

urlpatterns = [
    path('equipe/', views.add_equipe, name='equipes'),
    path('funcionario/', views.add_funcionario, name='funcionario'),
]

mecanica/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.start, name='main' ),
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('servicos/', include('servicos.urls')),
    path('equipe/', include('equipe.urls')),
    path('pedido/', include('pedido.urls')),
    path('lista/', views.listas, name='listas')
]

pedido/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pedido', views.pedido, name="pedido"),
    path('achar_carro/', views.achar_carro, name="carro"),
    path('calendario/', views.calendario, name='calendario'),
    path('update/<int:id>', views.update, name="update"),
    path('finalizar/', views.finalizar, name="finalizar")
]

servicos/urls.py
from django.urls import path
from . import views

app_name = 'servicos'

urlpatterns = [
    path('servicos/', views.servicos, name='servicos'),
    path('pecas/', views.pecas, name='pecas'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    {% block 'head' %}{% endblock %}
    <title>{% block 'title' %}{% endblock %}</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins" , sans-serif;
}
.sidebar{
  position: fixed;
  left: 0;
  top: 0;
  height: 100%;
  width: 78px;
  background: #411f2d;
  padding: 6px 14px;
  z-index: 99;
  transition: all 0.5s ease;
}
.sidebar.open{
  width: 250px;
}
.sidebar .logo-details{
  height: 60px;
  display: flex;
  align-items: center;
  position: relative;
}
.sidebar .logo-details .icon{
  opacity: 0;
  transition: all 0.5s ease;
}
.sidebar .logo-details .logo_name{
  color: #fff;
  font-size: 20px;
  font-weight: 600;
  opacity: 0;
  transition: all 0.5s ease;
}
.sidebar.open .logo-details .icon,
.sidebar.open .logo-details .logo_name{
  opacity: 1;
}
.sidebar .logo-details #btn{
  position: absolute;
  top: 50%;
  right: 0;
  transform: translateY(-50%);
  font-size: 22px;
  transition: all 0.4s ease;
  font-size: 23px;
  text-align: center;
  cursor: pointer;
  transition: all 0.5s ease;
}
.sidebar.open .logo-details #btn{
  text-align: right;
}
.sidebar i{
  color: #fff;
  height: 60px;
  min-width: 50px;
  font-size: 28px;
  text-align: center;
  line-height: 60px;
}
.sidebar .nav-list{
  margin-top: 20px;
  height: 100%;
}
.sidebar li{
  position: relative;
  margin: 8px 0;
  list-style: none;
}
.sidebar li .tooltip{
  position: absolute;
  top: -20px;
  left: calc(100% + 15px);
  z-index: 3;
  background: #fff;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 15px;
  font-weight: 400;
  opacity: 0;
  white-space: nowrap;
  pointer-events: none;
  transition: 0s;
}
.sidebar li:hover .tooltip{
  opacity: 1;
  pointer-events: auto;
  transition: all 0.4s ease;
  top: 50%;
  transform: translateY(-50%);
}
.sidebar.open li .tooltip{
  display: none;
}
.sidebar input{
  font-size: 15px;
  color: #FFF;
  font-weight: 400;
  outline: none;
  height: 50px;
  width: 100%;
  width: 50px;
  border: none;
  border-radius: 12px;
  transition: all 0.5s ease;
  background: #ac4147;
}
.sidebar.open input{
  padding: 0 20px 0 50px;
  width: 100%;
}
.sidebar .bx-search{
  position: absolute;
  top: 50%;
  left: 0;
  transform: translateY(-50%);
  font-size: 22px;
  background: #ac4147;
  color: #FFF;
}
.sidebar.open .bx-search:hover{
  background: #ac4147;
  color: #FFF;
}
.sidebar .bx-search:hover{
  background: #FFF;
  color: #ac4147;
}
.sidebar li a{
  display: flex;
  height: 100%;
  width: 100%;
  border-radius: 12px;
  align-items: center;
  text-decoration: none;
  transition: all 0.4s ease;
  background: #ac4147;
}
.sidebar li a:hover{
  background: #FFF;
}
.sidebar li a .links_name{
  color: #fff;
  font-size: 15px;
  font-weight: 400;
  white-space: nowrap;
  opacity: 0;
  pointer-events: none;
  transition: 0.4s;
}
.sidebar.open li a .links_name{
  opacity: 1;
  pointer-events: auto;
}
.sidebar li a:hover .links_name,
.sidebar li a:hover i{
  transition: all 0.5s ease;
  color: #ac4147;
}
.sidebar li i{
  height: 50px;
  line-height: 50px;
  font-size: 18px;
  border-radius: 12px;
}
.sidebar li.profile{
  position: fixed;
  height: 60px;
  width: 78px;
  left: 0;
  bottom: -8px;
  padding: 10px 14px;
  background: #ac4147;
  transition: all 0.5s ease;
  overflow: hidden;
}
.sidebar.open li.profile{
  width: 250px;
}
.sidebar li .profile-details{
  display: flex;
  align-items: center;
  flex-wrap: nowrap;
}
.sidebar li img{
  height: 45px;
  width: 45px;
  object-fit: cover;
  border-radius: 6px;
  margin-right: 10px;
}
.sidebar li.profile .name,
.sidebar li.profile .job{
  font-size: 15px;
  font-weight: 400;
  color: #fff;
  white-space: nowrap;
}
.sidebar li.profile .job{
  font-size: 12px;
}
.sidebar .profile #log_out{
  position: absolute;
  top: 50%;
  right: 0;
  transform: translateY(-50%);
  background: #ac4147;
  width: 100%;
  height: 60px;
  line-height: 60px;
  border-radius: 0px;
  transition: all 0.5s ease;
}
.sidebar.open .profile #log_out{
  width: 50px;
  background: none;
}
.home-section{
  position: relative;
  min-height: 100vh;
  top: 0;
  background: #2A2A2A;
  left: 78px;
  color: white;
  width: calc(100% - 78px);
  transition: all 0.5s ease;
  z-index: 2;
}
.sidebar.open ~ .home-section{
  left: 250px;
  width: calc(100% - 250px);
}
.home-section .text{
  display: inline-block;
  color: #ac4147;
  font-size: 25px;
  font-weight: 500;
  margin: 18px
}
@media (max-width: 420px) {
  .sidebar li .tooltip{
    display: none;
  }
}
    </style>
  </head>
  <body>
    
    <div class="sidebar">
        <div class="logo-details">
            <div class="logo_name">Mecânica</div>
            <i class='bx bx-menu' id="btn" ></i>
        </div>
        <ul class="nav-list">
          <li>
            <a href="{% url 'listas' %}">
              <i class='bx bx-list-ul'></i>
              <span class="links_name">Ver lista</span>
            </a>
            <span class="tooltip">Ver lista</span>
          </li>
          <li>
            <a href="{% url 'pedido:pedido' %}">
              <i class='bx bx-grid-alt'></i>
              <span class="links_name">Fazer pedido</span>
            </a>
            <span class="tooltip">Fazer pedido</span>
          </li>
          <li>
          <a href="{% url 'clientes' %}">
            <i class='bx bxs-user-circle'></i>
            <span class="links_name">Clientes</span>
          </a>
          <span class="tooltip">Clientes</span>
        </li>
        <li>
          <a href="{% url 'servicos:servicos' %}">
            <i class='bx bx-bookmarks'></i>
            <span class="links_name">Serviços</span>
          </a>
          <span class="tooltip">Serviços</span>
        </li>
        <li>
          <a href="{% url 'servicos:pecas' %}">
            <i class='bx bx-folder' ></i>
            <span class="links_name">Peças</span>
          </a>
          <span class="tooltip">Peças</span>
        </li>
        <li>
          <a href="{% url 'equipe:equipes' %}">
            <i class='bx bx-group'></i>
            <span class="links_name">Equipe</span>
          </a>
          <span class="tooltip">Equipe</span>
        </li>
        <li>
          <a href="{% url 'equipe:funcionario'%}">
            <i class='bx bx-user-circle'></i>
            <span class="links_name">Funcionario</span>
          </a>
          <span class="tooltip">Funcionario</span>
        </li>
        <li>
          <a href="{% url 'pedido:calendario'%}">
            <i class='bx bxs-calendar'></i>
            <span class="links_name">Calendario</span>
          </a>
          <span class="tooltip">Calendario</span>
        </li>
        </ul>
      </div>
      
      <section class="home-section">
          {% block 'dashboard'%}
          {% endblock %}

      </section>

    {% block 'body' %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <script>
      let sidebar = document.querySelector(".sidebar");
let closeBtn = document.querySelector("#btn");
let searchBtn = document.querySelector(".bx-search");

closeBtn.addEventListener("click", ()=>{
    sidebar.classList.toggle("open");
    menuBtnChange();
});

searchBtn.addEventListener("click", ()=>{ 
    sidebar.classList.toggle("open");
    menuBtnChange();
});

function menuBtnChange() {
if(sidebar.classList.contains("open")){
    closeBtn.classList.replace("bx-menu", "bx-menu-alt-right");
}else {
    closeBtn.classList.replace("bx-menu-alt-right","bx-menu");
}
}
    </script>
  </body>
</html>

templates/listas.html
{% extends "base.html" %}
{% load static %}

{% block 'dashboard' %}
<div class="container">
    <div>
        <h1>Listas</h1>
    </div>
    <div class="row">
        <div class="col-md">
            <a href="#cliente">
                <p class="btn btn-danger form-control"> Clientes </p>
            </a>
        </div>
        <div class="col-md">
            <a href="#servico">
                <p class="btn btn-danger form-control"> Serviços </p>
            </a>
        </div>
        <div class="col-md">
            <a href="#peca">
                <p class="btn btn-danger form-control"> Peças </p>
            </a>
        </div>
        <div class="col-md">
            <a href="#fun">
                <p class="btn btn-danger form-control"> Funcionarios </p>
            </a>
        </div>
    </div>
    <div >
        <h2 id="cliente">Clientes</h2>
        <table class="table" style="color: aliceblue;">
            <thead>
                <tr>
                    <th scope="col"> ID </th>
                    <th scope="col"> Nome </th>
                    <th scope="col"> Sobrenome </th>
                    <th scope="col"> Email </th>
                    <th scope="col"> Cpf </th>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr id="{{cliente.id}}">
                    <td name="id" scope="row">{{ cliente.id }}</td>
                    <td name="nome" >{{ cliente.nome }}</td>
                    <td name="sobrenome">{{ cliente.sobrenome }}</td>
                    <td name="email">{{ cliente.email }}</td>
                    <td name="cpf">{{ cliente.cpf }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
    <div>
        <h2 id="servico">Serviços</h2>
        <table class="table" style="color: aliceblue;">
            <thead>
                <tr>
                    <th scope="col"> ID </th>
                    <th scope="col"> Nome </th>
                    <th scope="col"> Preco </th>
                    <th scope="col"> Descrição </th>
            </thead>
            <tbody>
                {% for serviço in serviços %}
                <tr id="{{serviço.id}}">
                    <td name="id" scope="row">{{ serviço.id }}</td>
                    <td name="nome" >{{ serviço.nome }}</td>
                    <td name="preco">R${{ serviço.preco }}</td>
                    <td name="descrição">{{ serviço.descrição }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
    <div>
        <h2 id="peca">Peças</h2>
        <table class="table" style="color: aliceblue;">
            <thead>
                <tr>
                    <th scope="col"> ID </th>
                    <th scope="col"> Nome </th>
                    <th scope="col"> Preco </th>
                    <th scope="col"> Estoque </th>
            </thead>
            <tbody>
                {% for peca in pecas %}
                <tr id="{{peca.id}}">
                    <td name="id" scope="row">{{ peca.id }}</td>
                    <td name="nome" >{{ peca.nome }}</td>
                    <td name="preco">R${{ peca.preco }}</td>
                    <td name="quantidade">{{ peca.quantidade }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
    <div>
        <h2 id="fun">Funcionarios</h2>
        <table class="table" style="color: aliceblue;">
            <thead>
                <tr>
                    <th scope="col"> ID </th>
                    <th scope="col"> Nome </th>
                    <th scope="col"> Sobrenome </th>
                    <th scope="col"> Email </th>
                    <th scope="col"> Cpf </th>
                    <th scope="col"> Equipe </th>
            </thead>
            <tbody>
                {% for funcionario in funcionarios %}
                <tr id="{{funcionario.id}}">
                    <td name="id" scope="row">{{ funcionario.id }}</td>
                    <td name="nome" >{{ funcionario.nome }}</td>
                    <td name="sobrenome">{{ funcionario.sobrenome }}</td>
                    <td name="email">{{ funcionario.email }}</td>
                    <td name="cpf">{{ funcionario.cpf }}</td>
                    <td name="equipe">{{ funcionario.equipe }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
</div>
{% endblock%}

templates/start.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
{% endblock %}

{% block 'dashboard' %}
<div class="container">
    <div class="p-5" style="width: 90vw; height: 90vh;">
        <div>
            <h1 class="text-center fw-bold">Bem vindo a nossa <strong style="color:#ac4147;">MECÂNICA</strong>!</h1>
        </div>
        <div>
            <div>
                <img style="width: 70vw; margin-left: 5vw; filter: saturate(50%);" src="https://pngimg.com/uploads/ferrari/ferrari_PNG10632.png" alt="">
            </div>
    </div>
</div>
{% endblock%}