equipe/urls.py
from django.urls import path
from . import views

app_name = 'equipe'  # Defina o namespace para sua aplicação

urlpatterns = [
    path('equipe/', views.add_equipe, name='equipes'),
    path('funcionario/', views.add_funcionario, name='funcionario'),
]

mecanica/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.start, name='main' ),
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('servicos/', include('servicos.urls')),
    path('equipe/', include('equipe.urls')),
    path('pedido/', include('pedido.urls')),
    path('lista/', views.listas, name='listas')
]

pedido/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pedido', views.pedido, name="pedido"),
    path('achar_carro/', views.achar_carro, name="carro"),
    path('calendario/', views.calendario, name='calendario'),
    path('update/<int:id>', views.update, name="update"),
    path('finalizar/', views.finalizar, name="finalizar")
]

pedido/models.py
from django.db import models
from clientes.models import Carro, Cliente
from equipe.models import Equipe
from servicos.models import Servicos, Pecas

# Create your models here
class Requisicao(models.Model):
    carro = models.ForeignKey(Carro, on_delete=models.SET_NULL, null=True)
    descricao = models.TextField(max_length=1000)
    data_inicio = models.DateField()
    data_entrega = models.DateField(null=True)
    equipe = models.ForeignKey(Equipe, on_delete=models.SET_NULL, null=True)
    servico = models.ForeignKey(Servicos, on_delete=models.SET_NULL, null=True)
    pecas = models.ForeignKey(Pecas, on_delete=models.SET_NULL, null=True)
    valor_final = models.DecimalField(decimal_places=2, max_digits=8, null=True)

pedido/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from clientes.models import Carro, Cliente
from equipe.models import Equipe
from servicos.models import Servicos, Pecas
from .models import Requisicao
import re
from django.core import serializers
import json
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404

# Create your views here.
def pedido(request):
    if request.method == 'GET':
        equipe_list = Equipe.objects.all()
        return render(request, 'pedido.html', {'equipes':equipe_list})
    elif request.method == 'POST':
        descricao = request.POST.get('descricao_servico')
        data_inicio = request.POST.get('data')
        carro_id = request.POST.get('id_carro')
        print(carro_id)
        equipe_id = request.POST.get('equipe')
        equipe_selecionada = Equipe.objects.get(pk=equipe_id)

        requisicao = Requisicao(
            descricao = descricao,
            data_inicio = data_inicio,
            carro_id = carro_id,
            equipe_id = equipe_id,
        )
        requisicao.save()
        return HttpResponse('salvou requisição')

def achar_carro(request):
    if request.method == 'POST':
        placa = request.POST.get('placa')
        try:
            carro = get_object_or_404(Carro, placa=placa)
                        
            id_carro = json.loads(serializers.serialize('json', [carro]))[0]['pk']

            cliente = Cliente.objects.filter(nome = carro.cliente).first()
            cliente_nome = cliente.nome
            cliente_id = json.loads(serializers.serialize('json', [cliente]))[0]['pk']
            
            
            carro_info = {
                'id' : id_carro,
                'cliente': cliente_nome,
                'cliente_id': cliente_id,
                'carro': carro.carro,
                'ano': carro.ano,
            }
            return JsonResponse({'carro': carro_info})
        except Carro.DoesNotExist:
            carro_info = {
                'status': 'erro'
            }
            return JsonResponse({'status':carro_info})
        
def calendario(request):
    if request.method == 'GET':
        reqlist = Requisicao.objects.all()
        listaCompleta = []
        listaIncompleta = []
        for requisicao in reqlist:
            if requisicao.data_entrega is None:
                listaIncompleta.append(requisicao)
            else:
                listaCompleta.append(requisicao)

        return render(request, 'calendario.html', {'requisiçõesIncompletas': listaIncompleta, 'requisiçõesCompletas': listaCompleta})

@csrf_exempt
def update(request, id):
    requisição = Requisicao.objects.filter(id = id).first()
    carro = requisição.carro
    equipe = requisição.equipe

    pecas = Pecas.objects.all()
    servicos = Servicos.objects.all()

    jsonRequisição = json.loads(serializers.serialize('json',[requisição]))[0]['fields']
    idRequisição = json.loads(serializers.serialize('json',[requisição]))[0]['pk']

    data = {'id': idRequisição, 'fields':jsonRequisição}
    print(jsonRequisição)

    return render(request, 'update.html', {'carro': carro, 'equipe':equipe, 'data':data, 'pecas':pecas, 'servicos': servicos})

def finalizar(request):
    if request.method == "POST":
        try:
            id = request.POST.get('id')
            placacarro = request.POST.get('carro')
            carro = Carro.objects.filter(placa = placacarro).first()
            data_inicio = request.POST.get('data_inicio')
            equipe = request.POST.get('equipe')
            descricao = request.POST.get('descricao')
            data_entrega = request.POST.get('data_entrega')
            id_peca = request.POST.get('peca')
            quantidade = request.POST.get('quantidade')
            id_servico = request.POST.get('servico')

            if quantidade is not None:
                quantidade = int(quantidade)
            else:
                quantidade = 1  # Defina um valor padrão ou trate de acordo com a lógica do seu sistema

            peca = Pecas.objects.get(id=id_peca)
            servico = Servicos.objects.get(id=id_servico)

            valor_peca = peca.preco
            valor_servico = servico.preco

            valor_total = (valor_peca * quantidade) + valor_servico

            requisicao = get_object_or_404(Requisicao, id=id)
            requisicao.carro = carro
            requisicao.descricao = descricao
            requisicao.data_inicio = data_inicio
            requisicao.data_entrega = data_entrega
            requisicao.servico = servico
            requisicao.peca = peca
            requisicao.valor_final = valor_total
            requisicao.save()

            return HttpResponse("Pedido finalizado com sucesso!")
        except Exception as e:
            print("Erro ao finalizar pedido:", str(e))
            return HttpResponse("Ocorreu um erro ao finalizar o pedido. Por favor, tente novamente.")
    else:
        return HttpResponse("Método não permitido para esta rota.")

pedido/templates/calendario.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'clientes/css/clientes.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container">
    <h1>Calendario</h1>
    <table class="table" style="color: aliceblue;">
        <thead>
            <tr>
                <th scope="col"> ID </th>
                <th scope="col"> Placa do carro </th>
                <th scope="col"> Descrição do problema </th>
                <th scope="col"> Data de inicio </th>
                <th scope="col"> Equipe responsavel </th>
                <th scope="col"> Marcar como concluido </th>
            </tr>
        </thead>
        <tbody>
            {% for requisição in requisiçõesIncompletas %}
            <tr id="{{requisição.id}}">
                <td name="id" scope="row">{{ requisição.id }}</td>
                <td name="placa" >{{ requisição.carro }}</td>
                <td name="descricao">{{ requisição.descricao }}</td>
                <td name="data_inicio">{{ requisição.data_inicio }}</td>
                <td name="equipe">{{ requisição.equipe }}</td>
                <td>
                    <form action="{% url 'pedido:update' requisição.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit">
                            <i class="bx bxs-check-square"></i>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <h2>Histórico</h2>
    <table class="table" style="color: aliceblue;">
        <thead>
            <tr>
                <th scope="col"> ID </th>
                <th scope="col"> Placa do carro </th>
                <th scope="col"> Descrição do problema </th>
                <th scope="col"> Data de inicio </th>
                <th scope="col">Data final</th>
                <th scope="col"> Equipe responsavel </th>
                <th scope="col"> Valor Final </th>
            </tr>
        </thead>
        <tbody>
            {% for requisição in requisiçõesCompletas %}
            <tr>
                <td name="id" scope="row">{{ requisição.id }}</td>
                <td name="placa" >{{ requisição.carro }}</td>
                <td name="descricao">{{ requisição.descricao }}</td>
                <td name="data_inicio">{{ requisição.data_inicio }}</td>
                <td name="data_entrega">{{ requisição.data_entrega }}</td>
                <td name="equipe">{{ requisição.equipe }}</td>
                <td name="valorFinal">R$ {{ requisição.valor_final}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock%}

pedido/templates/pedido.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'clientes/css/clientes.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container">
    <div>
        <h1>Criar Pedido de Reparo</h1>
    </div>
    <form action="" method="post">{% csrf_token %}
        <p>Placa</p>
        <div class="row">
            <div class="col-md">
                <input type="text" name="placa" id="placa" required class="form-control">
            </div>
            <div class="col-md">
                <p class="btn btn-success" onclick="dados_carros()">Achar carro</p>
            </div>
        </div>
        <div id="carro_form" style="display: none;">
            <input type="number" name="id_carro" id="id_carro" hidden>
            <input type="number" name="id_cliente" id="id_cliente" hidden>
            <div class="row">
                <div class="col-md">
                    <p>Nome do carro:</p>
                    <input type="text" class="form-control btn-outline-light" id="nome" disabled>
                </div>
                <div class="col-md">
                    <p>Ano:</p>
                    <input type="number" name="" id="ano" class="form-control btn-outline-light" disabled>
                </div>
            </div>
            <div>
                <p>Proprietario</p>
                <input type="text" class="form-control btn-outline-light" id="cliente" disabled>
            </div>
        </div>
        <hr>
        <p>Descrição do Serviço</p>
        <textarea rows="6" class="form-control" name="descricao_servico" id="descricao_serv"></textarea>
        <div class="row">
            <div class="col-md">
                <p>Equipe:</p>
                <select name="equipe" id="equipe" class="form-control">
                    <option value="">Selecione uma Equipe...</option>
                    {% for equipe in equipes %}
                    <option value="{{ equipe.id }}">{{ equipe.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <p>Data:</p>
                <input type="date" name="data" id="data" class="form-control">
            </div>
        </div>
        <br>
        <button class="form-control btn btn-success" type="submit">Fazer Pedido</button>
    </form>
</div>
<script>
    function dados_carros() {
    const placa = document.getElementById('placa').value;
    console.log(placa);
    const csrf_token = document.querySelector('[name=csrfmiddlewaretoken]').value;
    
    const data = new FormData();
    data.append('placa', placa);

    fetch('/pedido/achar_carro/', {
        method: 'POST',
        headers: {
            'X-CSRFToken': csrf_token,
        },
        body: data,
    })
    .then(function(result) {
        return result.json();
    })
    .then(function(data) {
        console.log(data.carro.cliente_id);

        document.getElementById('carro_form').style.display = 'block';
        document.getElementById('nome').value = data.carro.carro;
        document.getElementById('ano').value = data.carro.ano;
        document.getElementById('cliente').value = data.carro.cliente;
        document.getElementById('id_carro').value = data.carro.id;
        document.getElementById('id_cliente').value = data.carro.cliente_id;
        // Adicione outras atribuições de valores aos campos do formulário conforme necessário
    })
}
</script>
{% endblock%}

pedido/templates/update.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'clientes/css/clientes.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container">
    <h1>Fazer update de serviço</h1>
    <div>
        <form action="{% url 'pedido:finalizar' %}" method="post">{% csrf_token %}
            <input type="text" name="id" value="{{data.id}}" hidden>
            <div class="border border-danger">
                <div class="container p-3">
                    <div class="row">
                        <div class="col-md">
                            <p>Placa do carro:</p>
                            <input name="carro" class="form-control" type="text" value="{{carro}}">
                        </div>
                        <div class="col-md">
                            <p>Data da manutenção:</p>
                            <input name="data_inicio" class="form-control" type="date" value="{{data.fields.data_inicio}}">
                        </div>
                        <div class="col-md">
                            <p>Equipe responsavel:</p>
                            <input name="equipe" class="form-control" type="text" value="{{equipe}}">
                        </div>
                    </div>
                    <p>Descrição do problema:</p>
                    <textarea class="form-control" name="descricao">{{data.fields.descricao}}</textarea>
                </div>
            </div>
            <div class="container p-3">
                <p>Data de entrega:</p>
                <input class="form-control" type="date" name="data_entrega" id="data_entrega">
                <div class="row">
                    <div class="col-md">
                        <p>Peça utilizada</p>
                        <select class="form-control" name="peca" id="">
                            {% for peca in pecas%}
                            <option value="{{peca.id}}">{{peca.nome}} - R$ {{peca.preco}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md">
                        <p>Quantidade</p>
                        <input name="quantidade" class="form-control" type="number">
                    </div>
                </div>
                <p>Serviço Prestado</p>
                <select class="form-control" name="servico" id="">
                    {% for servico in servicos %}
                    <option value="{{servico.id}}">{{servico.nome}} - R$ {{servico.preco}}</option>
                    {% endfor %}
                </select>
                <br>
                <button class="btn btn-success form-control" type="submit">Finalizar Serviço</button>
            </div>
        </form>
    </div>
</div>
{% endblock%}